set-option -g default-shell /usr/bin/zsh
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

# Set status bar colors
#set-option -g status-bg white
#set-option -g status-fg black

set -g prefix C-Space
unbind C-b

# Default Prefix to Ctrl Space
bind C-Space send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!";

# Set Status to Top
set -g status-position bottom

# Splitting Window
unbind %
bind '\' split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z
bind C-l send-key C-l 

set -g mouse on

# Set window numeric from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Enable vim Mode
set-window-option -g mode-keys vi

bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection

#unbind -T copy-mode-vi MouseDragEndPane

# Plugins
set -g @plugin "tmux-plugins/tpm"

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'o0th/tmux-nova'

set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

set -g @nova-pane-active-border-style "#44475a"
set -g @nova-pane-border-style "#282a36"
set -g @nova-status-style-bg "#2e3540"
set -g @nova-status-style-fg "#4c566a"
set -g @nova-status-style-active-bg " 	#ff6583"
set -g @nova-status-style-active-fg "#2e3540"
set -g @nova-status-style-double-bg "#2d3540"

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#a3d97c #2e3440"

set -g @nova-segment-whoami "#(whoami)"
set -g @nova-segment-whoami-colors "#a3d97c #2e3440"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"

#set -g @plugin 'maxpetretta/tmux-monokai-pro'

#set -g @monokai-plugins " "
#set -g @monokai-show-powerline true

# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

run ~/.tmux/plugins/tpm/tpm
